/* ============================================================
   Shared data, plan model, seed content
   Exported to window so other Babel scripts can use it.
   ============================================================ */

// -- Plans --------------------------------------------------------------
const PLANS = {
  free: {
    id: "free",
    name: "Brand Scan",
    price: "Zdarma",
    priceNote: "14 dní přístup",
    tagline: "Ochutnej, co Lucifera umí",
    credits: 600,
    creditsInit: 600,
    features: [
      "3 příspěvky ke stažení",
      "Vizuální knihovna — náhled",
      "Index značky",
    ],
    lockedSections: ["brand-dna-full", "rtg", "planner"],
    badge: null,
    posts: { videos: 0, grafika: 3, carousels: 0 },
  },
  start: {
    id: "start",
    name: "RTG Start",
    price: "2 900 Kč",
    priceNote: "měsíčně · 3 příspěvky týdně",
    tagline: "Obsah na autopilotu, tvůj styl",
    credits: 4200,
    creditsInit: 6000,
    features: [
      "2 videa / 8 grafik měsíčně",
      "Plná Brand DNA strategie",
      "Plánovač obsahu",
      "Strateg doporučení",
    ],
    lockedSections: ["planner-pro"],
    badge: null,
    posts: { videos: 2, grafika: 8, carousels: 0 },
  },
  plus: {
    id: "plus",
    name: "RTG Plus",
    price: "4 900 Kč",
    priceNote: "měsíčně · 6 příspěvků týdně",
    tagline: "Pro ty, co chtějí tempo i hloubku",
    credits: 9800,
    creditsInit: 12000,
    features: [
      "4 videa / 16 grafik / 4 carousely",
      "Prémiová Brand DNA",
      "Pokročilý plánovač",
      "Měsíční strategické volání",
    ],
    lockedSections: [],
    badge: "Nejoblíbenější",
    posts: { videos: 4, grafika: 16, carousels: 4 },
  },
  pro: {
    id: "pro",
    name: "RTG Pro",
    price: "7 900 Kč",
    priceNote: "měsíčně · 11 příspěvků týdně",
    tagline: "Pro značky, co chtějí dominovat",
    credits: 18400,
    creditsInit: 22000,
    features: [
      "8 videí / 30 grafik / 8 carouselů",
      "Dedikovaný strateg",
      "Týdenní optimalizace",
      "Priority support",
    ],
    lockedSections: [],
    badge: null,
    posts: { videos: 8, grafika: 30, carousels: 8 },
  },
  pvi: {
    id: "pvi",
    name: "Prémiová vizuální identita",
    price: "od 49 000 Kč",
    priceNote: "jednorázově",
    tagline: "Kompletní přestavba značky",
    credits: 0,
    creditsInit: 0,
    features: [
      "Kompletní Brand DNA dokument",
      "Vizuální identita na míru",
      "Fotografické focení",
      "AI avatar klienta",
    ],
    lockedSections: [],
    badge: "Prémium",
    posts: { videos: 0, grafika: 0, carousels: 0 },
  },
};

// -- Seed content --------------------------------------------------------
const BRAND = {
  name: "Studio Lucifera",
  handle: "studiolucifera.cz",
  initials: "SL",
  score: 75,
  archetype: "Kreátor",
  positioning: "Profesionální portréty pro herce a podnikatele",
  tone: "Osobní a profesionální",
  audience: "Herci a podnikatelé",
  pillars: [
    { key: "hodnota", label: "Hodnota", score: 8, tone: "stable" },
    { key: "energie", label: "Energie", score: 7, tone: "stable" },
    { key: "archit", label: "Architektura", score: 7, tone: "stable" },
    { key: "identita", label: "Identita", score: 6, tone: "warn" },
    { key: "duvera", label: "Důvěra", score: 5, tone: "warn" },
  ],
  palette: [
    { hex: "#f0e8c8", label: "Krémová", mood: "Warm" },
    { hex: "#e9d4c8", label: "Pudrová" },
    { hex: "#f5ede4", label: "Slonovina" },
    { hex: "#e8d0c0", label: "Pšenice" },
    { hex: "#ddd0bc", label: "Písek" },
    { hex: "#e8dcc8", label: "Lněná" },
    { hex: "#f0e8d8", label: "Mléčná" },
    { hex: "#e4d4bc", label: "Karamel" },
    { hex: "#ecdcc0", label: "Med" },
    { hex: "#f5e8d4", label: "Marcipán" },
  ],
  paletteGroups: [
    { id: "kremova", label: "Krémová & jemná", active: true, swatch: "#e9d4c8" },
    { id: "zemita", label: "Zemitá & přírodní", active: false, swatch: "#7a6a4a" },
    { id: "chladna", label: "Chladná & moderní", active: false, swatch: "#c8d4e0" },
    { id: "tmava", label: "Tmavá & dramatická", active: false, swatch: "#1c1b1a" },
    { id: "tepla", label: "Teplá & zlatá", active: false, swatch: "#c9a24a" },
  ],
};

const POSTS_SEED = [
  {
    id: "p1",
    type: "Foto",
    kind: "reel",
    source: "Vizuální banka",
    aspect: "9:16",
    duration: "15s",
    img: "assets/portrait-3.jpg",
    title: "Buďte autentičtí, nezapomenutelní",
    caption: "Vaše prezentace v více než jen obrázek — je to nástroj pro nové příležitosti.",
    hashtag: "#StudioLucifera",
    status: "pending",
  },
  {
    id: "p2",
    type: "Foto",
    kind: "reel",
    source: "Archiv Lucifera",
    aspect: "9:16",
    duration: "12s",
    img: "assets/portrait-7.jpg",
    title: "Otevřete dveře, které jste neviděli.",
    caption: "Kombinujeme fotografie s AI pro nezapomenutelný vizuální zážitek.",
    hashtag: "#StudioLucifera",
    status: "pending",
  },
  {
    id: "p3",
    type: "Grafika",
    kind: "post",
    source: "Vizuální banka",
    aspect: "1:1",
    img: "assets/grafika-a.jpg",
    title: "Buďte autentičtí, nezapomenutelní",
    caption: "Vaše prezentace v více než jen obrázek — je to nástroj pro nové příležitosti.",
    hashtag: "#StudioLucifera",
    status: "pending",
  },
  {
    id: "p4",
    type: "Grafika",
    kind: "post",
    source: "Archiv Lucifera",
    aspect: "1:1",
    img: "assets/grafika-b.jpg",
    title: "Otevřete dveře, které jste neviděli, že existují.",
    caption: "Kombinujeme fotografie s AI pro nezapomenutelný vizuální zážitek.",
    hashtag: "#StudioLucifera",
    status: "pending",
  },
];

const LIBRARY_IMAGES = [
  { src: "assets/portrait-1.jpg", label: "Reels vibe", id: "l1" },
  { src: "assets/portrait-2.jpg", label: "Feed lifestyle", id: "l2" },
  { src: "assets/portrait-5.jpg", label: "Carousel BG", id: "l3" },
  { src: "assets/portrait-6.jpg", label: "Quote post", id: "l4" },
  { src: "assets/portrait-8.jpg", label: "Story moment", id: "l5" },
  { src: "assets/portrait-9.jpg", label: "Reels vibe", id: "l6" },
  { src: "assets/portrait-10.jpg", label: "Feed lifestyle", id: "l7" },
  { src: "assets/portrait-11.jpg", label: "Carousel BG", id: "l8" },
  { src: "assets/portrait-12.jpg", label: "Story moment", id: "l9" },
  { src: "assets/portrait-4.jpg", label: "Reels vibe", id: "l10" },
  { src: "assets/portrait-3.jpg", label: "Quote post", id: "l11" },
  { src: "assets/portrait-7.jpg", label: "Feed lifestyle", id: "l12" },
];

const SCHEDULE_SEED = [
  { day: "Po", date: "22", type: "Reel",     pillar: "Portfolio",    hook: "Před & po retuši — 15s",       img: "assets/portrait-1.jpg",  time: "09:00" },
  { day: "Út", date: "23", type: "Carousel", pillar: "Vzdělávací",   hook: "5 tipů pro focení hlavu",      img: "assets/portrait-5.jpg",  time: "11:30" },
  { day: "St", date: "24", type: "Story",    pillar: "Zákulisí",     hook: "Atelier check-in",             img: "assets/portrait-2.jpg",  time: "17:00" },
  { day: "Čt", date: "25", type: "Reel",     pillar: "Testimonial",  hook: "„Cítím se jako doma.“",        img: "assets/portrait-8.jpg",  time: "18:30" },
  { day: "Pá", date: "26", type: "Post",     pillar: "Osobnost",     hook: "Proč portrét není selfie",     img: "assets/portrait-6.jpg",  time: "10:00" },
  { day: "So", date: "27", type: "Story",    pillar: "Komunita",     hook: "Q&A s Katarínou",              img: "assets/portrait-9.jpg",  time: "20:00" },
  { day: "Ne", date: "28", type: "Reel",     pillar: "Portfolio",    hook: "Top výběr týdne",              img: "assets/portrait-10.jpg", time: "19:00" },
  { day: "Út", date: "30", type: "Carousel", pillar: "Portfolio",    hook: "Světlo v ateliéru",            img: "assets/portrait-11.jpg", time: "11:00" },
  { day: "Čt", date: "02", type: "Post",     pillar: "Osobnost",     hook: "Jedna věc, co změnila vše",    img: "assets/portrait-12.jpg", time: "09:30" },
  { day: "Pá", date: "03", type: "Reel",     pillar: "Vzdělávací",   hook: "3 chyby při focení",           img: "assets/portrait-4.jpg",  time: "18:00" },
];

window.LUCIFERA = { PLANS, BRAND, POSTS_SEED, LIBRARY_IMAGES, SCHEDULE_SEED };
